# Créer un disque persistant de 10 Go dans la zone europe-west1-b
# gcloud compute disks create my-data-disk --size=10GB --zone=europe-west1-b
apiVersion: v1
kind: Pod
metadata:
  name: test-gce-pd
spec:
  containers:
  - image: registry.k8s.io/test-webserver
    name: test-container
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    volumeMounts:
    - mountPath: /test-gce
      name: test-volume
      readOnly: false
  volumes:
  - name: test-volume
    # Ce volume GCE Persistent Disk doit déjà exister.
    gcePersistentDisk:
      pdName: my-data-disk
      fsType: ext4
